project:
  type: website
  # render:
  #   - index.qmd
  #   - contributors.qmd

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - contributors.qmd
      - Setup.qmd
      - materials.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

