---
title: "Contributors"
---

### This project was ideated and founded by **Professor Thema Monroe-White**

-   Associate Professor of Artificial Intelligence and Innovation Policy in the Schar School of Policy and Government and Department of Computer Science (joint) at George Mason University

-   [ORCID](https://orcid.org/0000-0001-9212-5430)

-   [Website](https://schar.gmu.edu/profiles/tmonroew)

### The team that developed the materials for this website is composed of:

-   **Diego Kozlowski**:

    -   École de bibliothéconomie et des sciences de l'information, Université de Montréal.

    -   [ORCID](https://orcid.org/0000-0002-5396-3471)

-   **Laia Domenech Burin**:

    -   [ORCID](https://orcid.org/0000-0003-4576-3143)

-   **Carolina Pradier**:

    -   École de bibliothéconomie et des sciences de l'information, Université de Montréal.

    -   [ORCID](https://orcid.org/0009-0007-5058-6352)

-   **Germán Rosati**:

    -   CONICET / IDAES-UNSAM

    -   [ORCID](https://orcid.org/0000-0002-9775-0435)

-   **Natsumi S. Shokida**:

    -   École de bibliothéconomie et des sciences de l'information, Université de Montréal.

    -   [ORCID](https://orcid.org/0009-0008-9198-3888)

We are grateful for their dedication and contributions to this project.

### 
